services:

    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false  

    Maalls\FirebaseBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Migrations,Tests}'

    Maalls\FirebaseBundle\Service\Factory:
        arguments: 
          $url: '%env(FIREBASE_DATABASE_URL)%' 
          $key: '%env(FIREBASE_API_KEY)%'
    Maalls\FirebaseBundle\Service\Firebase:
        arguments: 
          $url: '%env(FIREBASE_DATABASE_URL)%' 
          $key: '%env(FIREBASE_API_KEY)%'
